@startuml

title Class Diagram for Admas University Student Clearance Management System

class Student {
    +studentID: String
    +name: String
    +department: String
    +requestClearance(): void
    +receiveClearancePaper(): void
}

class Registrar {
    +registrarID: String
    +name: String
    +verifyStudentRecord(): void
    +issueClearancePaper(): void
}

class DepartmentHead {
    +departmentID: String
    +name: String
    +validateStudentStatus(): void
}

class AcademicDean {
    +deanID: String
    +name: String
    +approveClearance(): void
}

class Finance {
    +financeID: String
    +name: String
    +checkFinancialClearance(): void
}

class Library {
    +libraryID: String
    +name: String
    +checkLibraryClearance(): void
}

class Store {
    +storeID: String
    +name: String
    +checkStoreClearance(): void
}
Student "1" -- "1" Registrar : > Requests clearance
Student "1" --"1" Library : < Validate Library Clearance
Student "1" -- "1" Finance: < Validate Financial Clearance
Student "1" -- "1" Store : < Validate Store Clearance
Registrar "1" -- "1" DepartmentHead : < Check Student Status
Registrar "1" -- "1" AcademicDean: < Clearance Approval
@enduml