@startuml seq_diagram

title Sequence Diagram for Admas University Student Clearance Management System

actor Student as Student
actor Department_Head as Department_Head
actor Registrar as Registrar
actor Academic_Dean as Academic_Dean
actor Finance as Finance
actor Library as Library


@enduml